driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: centos-7.0
  - name: debian-6.0.10
  - name: debian-7.7
  - name: fedora-19
  - name: fedora-20
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[php::default]
