sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=resource-test-centos-7
  - INSTANCE=resource-test-debian-8
  - INSTANCE=resource-test-debian-9
  - INSTANCE=resource-test-ubuntu-1404
  - INSTANCE=resource-test-ubuntu-1604
  - INSTANCE=resource-test-ubuntu-1804
  - INSTANCE=resource-test-amazonlinux
  - INSTANCE=resource-test-amazonlinux-2
  - INSTANCE=resource-test-opensuse-leap
  - INSTANCE=resource-test-centos-6

matrix:
  allow_failures:
  - INSTANCE=resource-test-amazonlinux
  - INSTANCE=resource-test-opensuse-leap
  - INSTANCE=resource-test-centos-6
  # CentOS-6 fails due to the candidate version not installing (PHP is too lower version 5.3 EOL :( )

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
